/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.AltaCamion;
import Datos.AltaChofer;
import Datos.AltaTrailer;
import Metodos.Metodos_Altas;
import Metodos.Metodos_sql;
import Puentes.puenteAltas;
import javax.swing.JOptionPane;

/**
 *
 * @author AlejandroSaenz
 */
public class Modificable extends javax.swing.JFrame {

    /**
     * Creates new form Modificable
     */
    public Modificable() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
  Metodos_Altas Metodos;
    void MostrarTablaChofer() {
    (new puenteAltas()).PuenteMostrarTablaChofer(Dr);
  }
void MostrarTablaCamion() {
    (new puenteAltas()).PuenteMostrarTablaCamion(Tr);
  }
    void MostrarTablaTrailer() {
    (new puenteAltas()).PuenteMostrarTablaTrailer(Tra);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tra = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Dr = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tr = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Modelo2 = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        Marca1 = new javax.swing.JTextField();
        por = new javax.swing.JTextField();
        Marca2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        Id1 = new javax.swing.JLabel();
        Id2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtDueño = new javax.swing.JTextField();
        Porcentaje1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Modelo3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(218, 165, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tra);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 350, 300));

        Dr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Dr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DrMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Dr);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 350, 300));

        Tr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tr);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 350, 300));

        jLabel1.setText("Driver");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setText("Truck");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        jLabel3.setText("Trailer");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, -1, -1));
        jPanel1.add(Modelo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 440, 130, 30));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 130, 30));
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 130, 30));
        jPanel1.add(Marca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 130, 30));
        jPanel1.add(por, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 130, 30));
        jPanel1.add(Marca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 390, 130, 30));

        jLabel4.setText("Id:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel5.setText("Id:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        jLabel6.setText("Id:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, -1, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1205, 450, 60, -1));

        jLabel7.setText("Frist Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel8.setText("Last Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel9.setText("Brand:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        jLabel10.setText("%");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, -1));

        jLabel11.setText("Brand:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, -1, -1));

        jLabel12.setText("Model:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 440, -1, -1));
        jPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 50, 20));
        jPanel1.add(Id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 364, 40, 20));
        jPanel1.add(Id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 364, 50, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar_16.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 410, 90, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 370, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar_16.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar_16.png"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 90, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, -1, -1));

        jLabel13.setText("%");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        txtDueño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDueñoKeyTyped(evt);
            }
        });
        jPanel1.add(txtDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 70, 30));

        Porcentaje1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Porcentaje1KeyTyped(evt);
            }
        });
        jPanel1.add(Porcentaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 70, 30));

        jLabel14.setText("Owner:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));
        jPanel1.add(Modelo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 130, 30));

        jLabel15.setText("Model:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      AdministrarUsuarios Ad=new AdministrarUsuarios();
      Ad.setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrMouseClicked
if (evt.getButton() == 1) {
            int fila = Dr.getSelectedRow();
            Id.setText(Dr.getValueAt(fila, 0).toString());
            this.Nombre.setText(this.Dr.getValueAt(fila, 1).toString());
            this.Apellido.setText(this.Dr.getValueAt(fila, 2).toString());
            Porcentaje1.setText(this.Dr.getValueAt(fila, 3).toString());

        }    
    }//GEN-LAST:event_DrMouseClicked

    private void TrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrMouseClicked
if (evt.getButton() == 1) {
            int fila = Tr.getSelectedRow();
            Id1.setText(Tr.getValueAt(fila, 0).toString());
            this.Marca1.setText(this.Tr.getValueAt(fila, 1).toString());
            this.Modelo3.setText(this.Tr.getValueAt(fila, 2).toString());
            this.txtDueño.setText(this.Tr.getValueAt(fila, 3).toString());
            this.por.setText(this.Tr.getValueAt(fila, 4).toString());

        }          // TODO add your handling code here:
    }//GEN-LAST:event_TrMouseClicked

    private void TraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraMouseClicked

        if (evt.getButton() == 1) {
            int fila = Tra.getSelectedRow();
            Id2.setText(Tra.getValueAt(fila, 0).toString());
            this.Marca2.setText(this.Tra.getValueAt(fila, 1).toString());
            this.Modelo2.setText(this.Tra.getValueAt(fila, 2).toString());

        }      
    }//GEN-LAST:event_TraMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if (Id2.getText().isEmpty() || this.Marca2.getText().isEmpty() || this.Modelo2.getText().isEmpty()) {
      JOptionPane.showMessageDialog(null, "please select a row ", "please select a row", 1);
    } else {
     AltaTrailer prod = new AltaTrailer();
     prod.setId(Integer.parseInt(Id2.getText()));
      prod.setBrand(Marca2.getText());
      prod.setModel(Modelo2.getText());
      
      (new puenteAltas()).PuenteActualizarTrailer(prod);
      
      Id2.setText("");
      Marca2.setText("");
      Modelo2.setText("");
      MostrarTablaTrailer();
    }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 if (Id.getText().isEmpty() || this.Nombre.getText().isEmpty() || this.Apellido.getText().isEmpty()) {
      JOptionPane.showMessageDialog(null, "please select a row ", "please select a row", 1);
    } else {
     AltaChofer prod = new AltaChofer();
     prod.setId(Integer.parseInt(Id.getText()));
      prod.setNombre(Nombre.getText());
      prod.setApellidos(Apellido.getText());
      
      (new puenteAltas()).PuenteEliminarChofer(prod);
      
      Id.setText("");
      Nombre.setText("");
      Apellido.setText("");
      Porcentaje1.setText("");
      MostrarTablaChofer();
    }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if (Id1.getText().isEmpty() || this.Marca1.getText().isEmpty() || this.por.getText().isEmpty()) {
      JOptionPane.showMessageDialog(null, "please select a row ", "please select a row", 1);
    } else {
     AltaCamion prod = new AltaCamion();
     prod.setId(Integer.parseInt(Id1.getText()));
      prod.setBrand(Marca1.getText());
      prod.setModel(por.getText());
      
      (new puenteAltas()).PuenteEliminarCamion(prod);
      
      Id1.setText("");
      Marca1.setText("");
      por.setText("");
      MostrarTablaCamion();
    }        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if (Id2.getText().isEmpty() || this.Marca2.getText().isEmpty() || this.Modelo2.getText().isEmpty()) {
      JOptionPane.showMessageDialog(null, "please select a row ", "please select a row", 1);
    } else {
     AltaTrailer prod = new AltaTrailer();
     prod.setId(Integer.parseInt(Id2.getText()));
      prod.setBrand(Marca2.getText());
      prod.setModel(Modelo2.getText());
      
      (new puenteAltas()).PuenteEliminarTrailer(prod);
      
      Id2.setText("");
      Marca2.setText("");
      Modelo2.setText("");
      MostrarTablaTrailer();
    }          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
if (Id.getText().isEmpty() || this.Nombre.getText().isEmpty() || this.Apellido.getText().isEmpty()) {
      JOptionPane.showMessageDialog(null, "please select a row ", "please select a row", 1);
    } else {
     AltaChofer prod = new AltaChofer();
     prod.setId(Integer.parseInt(Id.getText()));
      prod.setNombre(Nombre.getText());
      prod.setApellidos(Apellido.getText());
      prod.setPorcentaje(Integer.parseInt(Porcentaje1.getText()));
      (new puenteAltas()).PuenteActualizarChofer(prod);
      
      Id.setText("");
      Nombre.setText("");
      Apellido.setText("");
      Porcentaje1.setText("");
      MostrarTablaChofer();
    }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                                        
if (Id1.getText().isEmpty() || this.Marca1.getText().isEmpty() || this.por.getText().isEmpty()|| this.Modelo3.getText().isEmpty()|| this.txtDueño.getText().isEmpty()) {
      JOptionPane.showMessageDialog(null, "please select a row ", "please select a row", 1);
    } else {
     AltaCamion prod = new AltaCamion();
     prod.setId(Integer.parseInt(Id1.getText()));
      prod.setBrand(Marca1.getText());
      prod.setModel(Modelo3.getText());
      prod.setOwner(txtDueño.getText());
      prod.setPercentage(Float.parseFloat(por.getText()));
      
      (new puenteAltas()).PuenteActualizarCamion(prod);
      
      Id1.setText("");
      Marca1.setText("");
      por.setText("");
      txtDueño.setText("");
      por.setText("");
      MostrarTablaCamion();
    }           
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtDueñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDueñoKeyTyped
            // TODO add your handling code here:
    }//GEN-LAST:event_txtDueñoKeyTyped

    private void Porcentaje1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Porcentaje1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Porcentaje1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    public javax.swing.JTable Dr;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Id1;
    private javax.swing.JLabel Id2;
    private javax.swing.JTextField Marca1;
    private javax.swing.JTextField Marca2;
    private javax.swing.JTextField Modelo2;
    private javax.swing.JTextField Modelo3;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Porcentaje1;
    public javax.swing.JTable Tr;
    public javax.swing.JTable Tra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField por;
    private javax.swing.JTextField txtDueño;
    // End of variables declaration//GEN-END:variables
}
