/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.AltaViaje;
import Datos.ConexionBD;
import Puentes.puenteAltas;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author AlejandroSaenz
 */
public class ModificarViaje extends javax.swing.JFrame {
Statement sentenciaSQL;
  
  ConexionBD con;
  
  public static PreparedStatement sentencia_preparada;
  
  public static ResultSet resultado;
  
  public static String url;
  
  public static int Resultado_numero = 0;
    /**
     * Creates new form ModificarViaje
     */
    public ModificarViaje() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
      void MostrarTablaTicket() {
    (new puenteAltas()).PuenteMostrarTablaTicket(this.tt, this.buscar);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ticket = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtPeriod = new javax.swing.JTextField();
        txtViaje = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtDriverId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDetalle = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtTrailer = new javax.swing.JTextField();
        txtCamion = new javax.swing.JTextField();
        txtBOL = new javax.swing.JTextField();
        txtTicket = new javax.swing.JTextField();
        txtDueño = new javax.swing.JTextField();
        txtMillas = new javax.swing.JTextField();
        txtAgregadoPor = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        txtDriverPay = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtBDdetalle = new javax.swing.JTextField();
        txtBonusDriver = new javax.swing.JTextField();
        SJFS = new javax.swing.JTextField();
        txtSJFSPorcentaje = new javax.swing.JTextField();
        txtPorcentaje = new javax.swing.JTextField();
        txtBonusDetalle = new javax.swing.JTextField();
        txtBonus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tt = new javax.swing.JTable();
        P = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        PSJ = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(218, 165, 32));

        Ticket.setBackground(new java.awt.Color(218, 165, 32));
        Ticket.setForeground(new java.awt.Color(218, 165, 32));
        Ticket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ticket");
        Ticket.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 18, -1, -1));

        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        Ticket.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 11, 169, 29));
        Ticket.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 79, 169, 38));
        Ticket.add(txtPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 146, 169, 38));
        Ticket.add(txtViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 211, 169, 38));
        Ticket.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 275, 169, 37));
        Ticket.add(txtDriverId, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 349, 169, 37));
        Ticket.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 419, 169, 37));
        Ticket.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 474, 169, 37));
        Ticket.add(txtDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 169, 37));

        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        Ticket.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 169, 37));
        Ticket.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 169, 37));
        Ticket.add(txtTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 169, 37));
        Ticket.add(txtCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 169, 38));
        Ticket.add(txtBOL, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 169, 38));
        Ticket.add(txtTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 169, 38));
        Ticket.add(txtDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 169, 37));
        Ticket.add(txtMillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 169, 37));
        Ticket.add(txtAgregadoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 169, 37));
        Ticket.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 169, 37));
        Ticket.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 169, 38));
        Ticket.add(txtDriverPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 169, 38));
        Ticket.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 169, 38));
        Ticket.add(txtBDdetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 169, 37));
        Ticket.add(txtBonusDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 169, 37));
        Ticket.add(SJFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 169, 37));
        Ticket.add(txtSJFSPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 169, 37));

        txtPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcentajeActionPerformed(evt);
            }
        });
        Ticket.add(txtPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 169, 38));
        Ticket.add(txtBonusDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 169, 38));
        Ticket.add(txtBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 169, 38));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Ticket.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 14, -1, -1));

        jLabel2.setText("Id");
        Ticket.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 91, -1, -1));

        jLabel3.setText("Period");
        Ticket.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 158, -1, -1));

        jLabel4.setText("No_Trip");
        Ticket.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 223, -1, -1));

        jLabel5.setText("Id_Driver");
        Ticket.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 360, -1, -1));

        jLabel6.setText("Date");
        Ticket.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 286, -1, -1));

        jLabel7.setText("First Name");
        Ticket.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 430, -1, -1));

        jLabel8.setText("Last Name");
        Ticket.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 474, -1, -1));

        jLabel9.setText("Ticket");
        Ticket.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jLabel10.setText("BOL");
        Ticket.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jLabel11.setText("Truck");
        Ticket.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        jLabel12.setText("Trailer");
        Ticket.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jLabel13.setText("Weight");
        Ticket.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jLabel14.setText("Costo");
        Ticket.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        jLabel15.setText("Description");
        Ticket.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        jLabel16.setText("Amount");
        Ticket.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        jLabel17.setText("Driver Pay");
        Ticket.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jLabel18.setText("Year");
        Ticket.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        jLabel19.setText("Type");
        Ticket.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, -1));

        jLabel20.setText("Added By");
        Ticket.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        jLabel21.setText("Miles");
        Ticket.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        jLabel22.setText("Owner");
        Ticket.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, -1, -1));

        jLabel23.setText("Bonus");
        Ticket.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        jLabel24.setText("Bonus det");
        Ticket.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, -1, -1));

        jLabel25.setText("Ticket %");
        Ticket.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, -1));

        jLabel26.setText("SJFS %");
        Ticket.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        jLabel27.setText("SJFS");
        Ticket.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, -1, -1));

        jLabel28.setText("Bonus Driver");
        Ticket.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, -1, -1));

        jLabel29.setText("BDDetail");
        Ticket.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Ticket.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, -1));

        tt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tt);

        Ticket.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 1380, 80));
        Ticket.add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 100, 110, 30));

        jLabel30.setText("% chofer");
        Ticket.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 70, -1, -1));

        jLabel31.setText("% SJFS");
        Ticket.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 180, -1, -1));
        Ticket.add(PSJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 120, 30));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Ticket.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ticket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
  
     
     if (!this.buscar.getText().isEmpty()) {

            //this.txtB.setText("");
           

            MostrarTablaTicket();
            tt.setVisible(true);
            AltaViaje Prov = new AltaViaje();
            Prov.setTicket(this.buscar.getText());
          

        } else {
            JOptionPane.showMessageDialog(null, "Please fill all fields", "Warning", 1);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed
public void Calcular() {
      float PorcentajeTicket=(Float.parseFloat(txtPorcentaje.getText()));
      float resto= 100-PorcentajeTicket;
      float gasto;
      float Descuento;
      float porcentaje;
      float porcentaje2;
      float sueldo;
     gasto = (Float.parseFloat(txtCosto.getText()));
      //System.out.println(gasto);
     Descuento= (float) (gasto*(resto/100));
     // System.out.println(Descuento);
     porcentaje=Integer.parseInt(P.getText());
      
      porcentaje2=porcentaje/100;
    
     sueldo= (float) (Descuento*porcentaje2);
      
      //System.out.println(sueldo);
     txtCantidad.setText(""+Descuento);
     txtDriverPay.setText(""+sueldo);
     
   
    
  }
  public void Calcular2(){
    float total= (Float.parseFloat(txtCosto.getText()));
    float porcentaje=(Float.parseFloat(PSJ.getText()));
    porcentaje=porcentaje/100;
      Float SantaJulia=total*porcentaje;
      SJFS.setText(""+SantaJulia);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     
     if (!this.buscar.getText().isEmpty()) {

            //this.txtB.setText("");
           

            MostrarTablaTicket();
            tt.setVisible(true);
            AltaViaje Prov = new AltaViaje();
            Prov.setTicket(this.buscar.getText());
          

        } else {
            JOptionPane.showMessageDialog(null, "Please fill all fields", "Warning", 1);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttMouseClicked
if (evt.getButton() == 1) {
            int fila = tt.getSelectedRow();
            this.txtId.setText(tt.getValueAt(fila, 0).toString());
    this.txtPeriod.setText(tt.getValueAt(fila, 1).toString());
    this.txtViaje.setText(tt.getValueAt(fila, 2).toString());
    this.txtFecha.setText(tt.getValueAt(fila, 3).toString());
    this.txtDriverId.setText(tt.getValueAt(fila, 4).toString());
    this.txtNombre.setText(tt.getValueAt(fila, 5).toString());
    this.txtApellidos.setText(tt.getValueAt(fila, 6).toString());
    this.txtTicket.setText(tt.getValueAt(fila, 7).toString());
    this.txtBOL.setText(tt.getValueAt(fila, 8).toString());
    this.txtCamion.setText(tt.getValueAt(fila, 9).toString());
    this.txtTrailer.setText(tt.getValueAt(fila, 10).toString());
    this.txtPeso.setText(tt.getValueAt(fila, 11).toString());
    this.txtCosto.setText(tt.getValueAt(fila, 12).toString());
    this.txtDetalle.setText(tt.getValueAt(fila, 13).toString());
    this.txtCantidad.setText(tt.getValueAt(fila, 14).toString());
    this.txtDriverPay.setText(tt.getValueAt(fila, 15).toString());
    this.txtAño.setText(tt.getValueAt(fila, 16).toString());
    this.txtTipo.setText(tt.getValueAt(fila, 17).toString());
    this.txtAgregadoPor.setText(tt.getValueAt(fila, 18).toString());
    this.txtMillas.setText(tt.getValueAt(fila, 19).toString());
    this.txtDueño.setText(tt.getValueAt(fila, 20).toString());
    this.txtBonus.setText(tt.getValueAt(fila, 21).toString());
    this.txtBonusDetalle.setText(tt.getValueAt(fila, 22).toString());
    this.txtPorcentaje.setText(tt.getValueAt(fila,23).toString());
    this.txtSJFSPorcentaje.setText(tt.getValueAt(fila, 24).toString());
    this.SJFS.setText(tt.getValueAt(fila, 25).toString());
    this.txtBonusDriver.setText(tt.getValueAt(fila, 26).toString());
    this.txtBDdetalle.setText(tt.getValueAt(fila, 27).toString());
           
           // this.txtcontraseña.setText(this.TablaUsuario.getValueAt(fila, 4).toString());
            
            

        }             // TODO add your handling code here:
    }//GEN-LAST:event_ttMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if (txtId.getText().isEmpty() ) {
      JOptionPane.showMessageDialog(null, "please select a row ", "please select a row", 1);
    } else {
     
       String sql = "UPDATE viaje SET Id=?, Period=?,No_Trip=?, Date=?,Id_Driver=?,First_Name=?,Last_Name=?,"
               + "Ticket=?,BOL=?,Truck=?,Trailer=?,Weight=?,Cost_of_the_trip=?,Description_of_the_cost=?,"
               + "Amount=?,Driver_Pay=?,Year=?,Type=?,Added_By=?,Miles=?,Owner=?,"
               + "Bonus=?,Bonus_Details=?,Ticket_Percentage=?,SJFS_Percentage=?,S_J_F_S=?,Bonus_Driver=?,Details_Bonus_Driver=? WHERE Id=?";
    try {
      this.con = new ConexionBD();
      PreparedStatement sentencia_preparada = this.con.Conectarse().prepareStatement(sql);
      
      
           sentencia_preparada.setInt(1, Integer.parseInt(txtId.getText()));
     sentencia_preparada.setInt(2, Integer.parseInt(txtPeriod.getText()));
     sentencia_preparada.setInt(3, Integer.parseInt(txtViaje.getText()));
      sentencia_preparada.setString(4, txtFecha.getText());
     sentencia_preparada.setInt(5, Integer.parseInt(txtDriverId.getText()));
       sentencia_preparada.setString(6, txtNombre.getText());
      sentencia_preparada.setString(7, txtApellidos.getText());
      sentencia_preparada.setString(8, txtTicket.getText());
      sentencia_preparada.setString(9, txtBOL.getText());
      sentencia_preparada.setString(10, txtCamion.getText());
      sentencia_preparada.setString(11, txtTrailer.getText());
      sentencia_preparada.setFloat(12, Float.parseFloat(txtPeso.getText()));
      sentencia_preparada.setFloat(13, Float.parseFloat(txtCosto.getText()));
      sentencia_preparada.setString(14, txtDetalle.getText());
      sentencia_preparada.setFloat(15, Float.parseFloat(txtCantidad.getText()));
      sentencia_preparada.setFloat(16, Float.parseFloat(txtDriverPay.getText()));
   sentencia_preparada.setInt(17, Integer.parseInt(txtAño.getText()));
      sentencia_preparada.setString(18, txtTipo.getText());
      sentencia_preparada.setString(19, txtAgregadoPor.getText());
      sentencia_preparada.setString(20, txtMillas.getText());
      sentencia_preparada.setString(21, txtDueño.getText());
            sentencia_preparada.setFloat(22, Float.parseFloat(txtBonus.getText()));

      sentencia_preparada.setString(23, txtBonusDetalle.getText());
      sentencia_preparada.setString(24, txtPorcentaje.getText());
            sentencia_preparada.setFloat(25, Float.parseFloat(txtSJFSPorcentaje.getText()));
      sentencia_preparada.setFloat(26, Float.parseFloat(SJFS.getText()));
      sentencia_preparada.setFloat(27, Float.parseFloat(txtBonusDriver.getText()));

      sentencia_preparada.setString(28, txtBDdetalle.getText());
      sentencia_preparada.setString(29, txtId.getText());


      int n = sentencia_preparada.executeUpdate();
      if (n >= 0)
        JOptionPane.showMessageDialog(null, "modified data", "modified data", 1); 
      this.con.CerrarConexion();
    } catch (ClassNotFoundException ex) {
      JOptionPane.showMessageDialog(null, "Clase no encontrada..." + ex);
    } catch (InstantiationException ex) {
      JOptionPane.showMessageDialog(null, "Error de conexion..." + ex);
    } catch (IllegalAccessException ex) {
      JOptionPane.showMessageDialog(null, "Acceso ilegal a la base de datos..." + ex);
    } catch (SQLException ex) {
      JOptionPane.showMessageDialog(null, "Error de sentencia..." + ex);
    } 
    
  
   
      MostrarTablaTicket();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
if(txtCosto.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "Please enter an amount");
                                }
    else{
   Calcular();
   Calcular2();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void txtPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentajeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Login lo=new Login();
lo.setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField P;
    private javax.swing.JTextField PSJ;
    private javax.swing.JTextField SJFS;
    private javax.swing.JPanel Ticket;
    private javax.swing.JTextField buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tt;
    private javax.swing.JTextField txtAgregadoPor;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtBDdetalle;
    private javax.swing.JTextField txtBOL;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtBonusDetalle;
    private javax.swing.JTextField txtBonusDriver;
    private javax.swing.JTextField txtCamion;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDetalle;
    private javax.swing.JTextField txtDriverId;
    private javax.swing.JTextField txtDriverPay;
    private javax.swing.JTextField txtDueño;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMillas;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeriod;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPorcentaje;
    private javax.swing.JTextField txtSJFSPorcentaje;
    private javax.swing.JTextField txtTicket;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTrailer;
    private javax.swing.JTextField txtViaje;
    // End of variables declaration//GEN-END:variables
}
