/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Controlador.ControladorExcel;
import Datos.AltaDeduccionMecanico;
import Datos.AltaMecanico;
import Datos.AltaPago;
import Datos.AltaPagoMecanico;
import Datos.AltaPersonal;
import Datos.ConexionBD;
import Metodos.Metodos_Altas;
import Modelo.ModeloExcel;
import Puentes.puenteAltas;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author AlejandroSaenz
 */
public class NominaExtra extends javax.swing.JFrame {
String IdBorrar;
    /**
     * Creates new form NominaExtra
     */

Statement sentenciaSQL;
  ConexionBD con;

  public static PreparedStatement sentencia_preparada;
  
  public static ResultSet resultado;
  
  public static String url;
    public NominaExtra() {
        initComponents();
        txtnombre1.setEnabled(false);
        txtapellido1.setEnabled(false);
        setLocationRelativeTo(null);
    }
void MostrarTablaNomina() {
    (new puenteAltas()).PuenteMostrarTablaNominaStaff(tabla2, txtperi, txtnombre, txtapellido,año);
  }
void MostrarTablaNominaMecanico() {
    (new puenteAltas()).PuenteMostrarTablaNominaMecanico(TablaPagoMecanico, txtperi2, txtnombre1, txtapellido1,año1);
  }
void MostrarTablaDeduccionMecanico() {
        (new puenteAltas()).PuenteMostrarTablaDeduccionMecanico(TablaDeduccionMecanico, txtperi2, txtnombre1, txtapellido1, año1);
    }

public float pago(){
    int contar=tabla2.getRowCount();
    float suma=0;
    for (int i=0; i < contar;i++){
        suma=suma+Float.parseFloat(tabla2.getValueAt(i, 6).toString());
    }
return suma;}

public float bonus(){
    int contar=tabla2.getRowCount();
    float suma=0;
    for (int i=0; i < contar;i++){
        suma=suma+Float.parseFloat(tabla2.getValueAt(i, 7).toString());
    }
return suma;}



public float TotalPay(){
    float pago=Float.parseFloat(pay.getText());
   
    float bono=Float.parseFloat(bonus.getText());
   
     float total=(pago+bono);
return total;}

public float pago1(){
    int contar=TablaPagoMecanico.getRowCount();
    float suma=0;
    for (int i=0; i < contar;i++){
        suma=suma+Float.parseFloat(TablaPagoMecanico.getValueAt(i, 5).toString());
    }
return suma;}

public float SumaDeduccionYTD(){
    int contar=TablaDeduccionMecanicoYTD.getRowCount();
    float suma=0;
    for (int i=0; i < contar;i++){
        suma=suma+Float.parseFloat(TablaDeduccionMecanicoYTD.getValueAt(i, 1).toString());
    }
return suma;}


public float DeduccionMecanico(){
    int contar=TablaDeduccionMecanico.getRowCount();
    float suma=0;
    for (int i=0; i < contar;i++){
        suma=suma+Float.parseFloat(TablaDeduccionMecanico.getValueAt(i, 2).toString());
    }
return suma;}

public float bonus1(){
    int contar=TablaPagoMecanico.getRowCount();
    float suma=0;
    for (int i=0; i < contar;i++){
        suma=suma+Float.parseFloat(TablaPagoMecanico.getValueAt(i, 6).toString());
    }
return suma;}

public float deduccion1(){
    int contar=TablaPagoMecanico.getRowCount();
    float suma=0;
    for (int i=0; i < contar;i++){
        suma=suma+Float.parseFloat(TablaPagoMecanico.getValueAt(i, 7).toString());
    }
return suma;}

public float TotalPay1(){
    float pago=Float.parseFloat(txtsub.getText());
   float Deduccion=Float.parseFloat(txtDeduccion.getText());
    float bono=Float.parseFloat(bonus1.getText());
     float total=(pago+bono)-Deduccion;
return total;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtp = new javax.swing.JTextField();
        txtnombre = new javax.swing.JLabel();
        txtapellido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtperi = new javax.swing.JTextField();
        año = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        g1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        pay = new javax.swing.JTextField();
        bonus = new javax.swing.JTextField();
        nam = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        txtperi2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        año1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        g2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPagoMecanico = new javax.swing.JTable();
        txtm = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtsub = new javax.swing.JTextField();
        bonus1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaDeduccionMecanico = new javax.swing.JTable();
        txtnombre1 = new javax.swing.JTextField();
        txtapellido1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaSubTotal = new javax.swing.JTable();
        txtDeduccion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaTotalDeducciones = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaTotalPay = new javax.swing.JTable();
        txtDeduccionYTD = new javax.swing.JTextField();
        txtytds = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaYTDSubTotal = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        TablaDeduccionMecanicoYTD = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        TablaDeduccoinesYTDTotal = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        TablaDeduccionYTDMecanicoNombre = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        TablaTotalDeducciones2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(218, 165, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(228, 175, 42));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Staff");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id:");

        txtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpActionPerformed(evt);
            }
        });
        txtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpKeyTyped(evt);
            }
        });

        txtnombre.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre.setText("First Name");

        txtapellido.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtapellido.setForeground(new java.awt.Color(255, 255, 255));
        txtapellido.setText("Last_Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Period");

        txtperi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperiActionPerformed(evt);
            }
        });
        txtperi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtperiKeyTyped(evt);
            }
        });

        año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Year");

        g1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g1ActionPerformed(evt);
            }
        });

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla2);

        nam.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nam.setForeground(new java.awt.Color(255, 255, 255));
        nam.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pay");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bonus");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Pay");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(61, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel4)))
                                .addGap(240, 240, 240)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnombre)
                                            .addComponent(txtapellido))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(txtperi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtperi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtnombre)
                        .addGap(18, 18, 18)
                        .addComponent(txtapellido)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 589));

        txtperi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperi2ActionPerformed(evt);
            }
        });
        txtperi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtperi2KeyTyped(evt);
            }
        });
        jPanel1.add(txtperi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1073, 43, 45, 29));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Period");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1016, 49, -1, -1));

        año1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));
        jPanel1.add(año1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1192, 47, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mechanic");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 11, 66, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Year");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1148, 49, -1, -1));

        g2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g2ActionPerformed(evt);
            }
        });
        jPanel1.add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1189, 501, 65, 65));

        TablaPagoMecanico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TablaPagoMecanico);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 122, -1, 145));

        txtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmActionPerformed(evt);
            }
        });
        txtm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmKeyTyped(evt);
            }
        });
        jPanel1.add(txtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 43, 43, 29));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Id:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 49, -1, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 501, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Bonus");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(934, 472, -1, -1));
        jPanel1.add(txtsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 493, 67, 28));
        jPanel1.add(bonus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(934, 491, 67, 27));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total Pay");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 516, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SubTotal");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 472, 67, -1));
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 537, 67, 29));

        TablaDeduccionMecanico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaDeduccionMecanico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDeduccionMecanicoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaDeduccionMecanico);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 309, 231, 145));

        txtnombre1.setText("First Name:");
        jPanel1.add(txtnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 32, 108, -1));

        txtapellido1.setText("Last Name:");
        jPanel1.add(txtapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 70, 108, -1));

        TablaSubTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Sub Total:", null}
            },
            new String [] {
                "", ""
            }
        ));
        jScrollPane4.setViewportView(TablaSubTotal);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1145, 122, 170, 30));
        jPanel1.add(txtDeduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 493, 67, 28));

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Deduction");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 472, -1, -1));

        TablaTotalDeducciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Total:", null}
            },
            new String [] {
                "", ""
            }
        ));
        jScrollPane5.setViewportView(TablaTotalDeducciones);
        if (TablaTotalDeducciones.getColumnModel().getColumnCount() > 0) {
            TablaTotalDeducciones.getColumnModel().getColumn(1).setHeaderValue("");
        }

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 310, 170, 30));

        TablaTotalPay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Total Pay:", null}
            },
            new String [] {
                "", ""
            }
        ));
        jScrollPane6.setViewportView(TablaTotalPay);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1142, 424, 170, 30));
        jPanel1.add(txtDeduccionYTD, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 553, 67, 28));
        jPanel1.add(txtytds, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 553, 67, 28));

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("SubTotal YTD");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 532, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Deduction YTD");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 532, -1, -1));

        TablaYTDSubTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"YTD SubTotal:", null}
            },
            new String [] {
                "", ""
            }
        ));
        jScrollPane7.setViewportView(TablaYTDSubTotal);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1145, 160, 170, 30));

        TablaDeduccionMecanicoYTD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(TablaDeduccionMecanicoYTD);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 309, 231, 145));

        TablaDeduccoinesYTDTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"YTD Deduction:", null}
            },
            new String [] {
                "", ""
            }
        ));
        jScrollPane9.setViewportView(TablaDeduccoinesYTDTotal);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1142, 350, 170, 30));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 460, -1, -1));

        TablaDeduccionYTDMecanicoNombre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Deduction YTD:"}
            },
            new String [] {
                ""
            }
        ));
        jScrollPane10.setViewportView(TablaDeduccionYTDMecanicoNombre);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 170, 30));

        TablaTotalDeducciones2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Deduction:"}
            },
            new String [] {
                ""
            }
        ));
        jScrollPane11.setViewportView(TablaTotalDeducciones2);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void g1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g1ActionPerformed

    private void g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g2ActionPerformed

    private void txtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpActionPerformed
  if (!this.txtp.getText().isEmpty()) {
     
      AltaPersonal prov = new AltaPersonal();
      prov.setId(Integer.parseInt(this.txtp.getText()));
      (new puenteAltas()).PuenteBuscarPersonal(prov);
      this.txtnombre.setText("" + prov.getFirst_Name());
      this.txtapellido.setText("" + prov.getLast_Name());
     
      txtp.setText("");
      txtperi.requestFocus();
             
    } else {
      JOptionPane.showMessageDialog(null, "Enter a ID", "Warning", 1);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txtpActionPerformed

    private void txtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmActionPerformed
if (!this.txtm.getText().isEmpty()) {
     
      AltaMecanico prov = new AltaMecanico();
      prov.setId(Integer.parseInt(this.txtm.getText()));
      (new puenteAltas()).PuenteBuscarMecanico(prov);
      this.txtnombre1.setText("" + prov.getFirst_Name());
      this.txtapellido1.setText("" + prov.getLast_Name());
            

     txtperi2.requestFocus();
             
    } else {
      JOptionPane.showMessageDialog(null, "Enter a ID", "Warning", 1);
    }            // TODO add your handling code here:
    }//GEN-LAST:event_txtmActionPerformed

    private void txtperiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperiActionPerformed
if (this.txtperi.getText().isEmpty() || this.txtnombre.getText().isEmpty()||this.txtapellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all fields", "Warning", 1);
        }
        else if (!this.txtperi.getText().isEmpty() && !this.txtnombre.getText().isEmpty()&&!this.txtapellido.getText().isEmpty()) {

           // MostrarTablaNomina();
            AltaPago Prov = new AltaPago();
            (new puenteAltas()).PuenteMostrarTablaNominaStaff(tabla2,txtperi,txtnombre,txtapellido,año);
            Prov.setPeriod(Integer.parseInt(txtperi.getText()));
            Prov.setFirst_Name(this.txtnombre.getText());
            Prov.setLast_Name(this.txtapellido.getText());

            this.tabla2.setVisible(true);
            
            
           
            
            
            pay.setText(Float.toString(pago()));
            bonus.setText(Float.toString(bonus()));
          
             total.setText(Float.toString(TotalPay()));
             
        }          // TODO add your handling code here:
    }//GEN-LAST:event_txtperiActionPerformed

    private void txtperi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperi2ActionPerformed
if (this.txtperi2.getText().isEmpty() || this.txtnombre1.getText().isEmpty()||this.txtapellido1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all fields", "Warning", 1);
        }
        else if (!this.txtperi2.getText().isEmpty() && !this.txtnombre1.getText().isEmpty()&&!this.txtapellido1.getText().isEmpty()) {
          
           // MostrarTablaNomina();
            AltaPagoMecanico Prov = new AltaPagoMecanico();
            (new puenteAltas()).PuenteMostrarTablaNominaMecanico(TablaPagoMecanico,txtperi2,txtnombre1,txtapellido1,año1);
            Prov.setPeriod(Integer.parseInt(txtperi2.getText()));
            Prov.setFirst_Name(this.txtnombre1.getText());
            Prov.setLast_Name(this.txtapellido1.getText());

            this.TablaPagoMecanico.setVisible(true);
            AltaDeduccionMecanico Prov2 = new AltaDeduccionMecanico();
        (new puenteAltas()).PuenteMostrarTablaDeduccionMecanico(TablaDeduccionMecanico, txtperi2, txtnombre1, txtapellido1, año1);
            
            txtsub.setText(Float.toString(pago1()));
            bonus1.setText(Float.toString(bonus1()));
           txtDeduccion.setText(Float.toString(DeduccionMecanico()));
             txtTotal.setText(Float.toString(TotalPay1()));
             TablaSubTotal.setValueAt(txtsub.getText(), 0, 1);
              TablaTotalDeducciones.setValueAt(txtDeduccion.getText(), 0, 1);
              TablaTotalPay.setValueAt(txtTotal.getText(), 0, 1);
              
                 Metodos_Altas me = new Metodos_Altas();
me.ConsultaYTDMecanico(txtperi2, txtnombre1, txtapellido1, año1, txtytds);
 TablaYTDSubTotal.setValueAt(txtytds.getText(), 0, 1);
  me.MostrarTablaYTDDetalladoMecanico(TablaDeduccionMecanicoYTD, txtperi2, txtnombre1, txtapellido1, año1);
txtDeduccionYTD.setText(Float.toString(SumaDeduccionYTD()));
 TablaDeduccoinesYTDTotal.setValueAt(txtDeduccionYTD.getText(), 0, 1);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtperi2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ModeloExcel modeloE = new ModeloExcel();
        Sistema vistaE = new Sistema();
        ControladorExcel contraControladorExcel = new ControladorExcel(vistaE, modeloE);
        vistaE.setVisible(true);
        vistaE.nombreUsuario.setText(nam.getText());
        vistaE.setLocationRelativeTo(null); 
dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpKeyTyped
char car = evt.getKeyChar();
        if (car < '0' || car > '9')
        evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_txtpKeyTyped

    private void txtmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmKeyTyped
char car = evt.getKeyChar();
        if (car < '0' || car > '9')
        evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_txtmKeyTyped

    private void txtperiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtperiKeyTyped
char car = evt.getKeyChar();
        if (car < '0' || car > '9')
        evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_txtperiKeyTyped

    private void txtperi2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtperi2KeyTyped
char car = evt.getKeyChar();
        if (car < '0' || car > '9')
        evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_txtperi2KeyTyped

    private void TablaDeduccionMecanicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDeduccionMecanicoMouseClicked
if (evt.getButton() == 1) {
            int fila = TablaDeduccionMecanico.getSelectedRow();
          IdBorrar=(TablaDeduccionMecanico.getValueAt(fila, 0).toString());
            
            
            

        }        // TODO add your handling code here:
    }//GEN-LAST:event_TablaDeduccionMecanicoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if (IdBorrar==null) {
      JOptionPane.showMessageDialog(null, "please select a row ", "please select a row", 1);
    } else {
     int Id=Integer.parseInt(IdBorrar);
      try {
      String sql = "DELETE FROM deducciones_mecanico WHERE Id=" + Id;
      this.con = new ConexionBD();
      this.sentenciaSQL = this.con.Conectarse().createStatement();
      int n = this.sentenciaSQL.executeUpdate(sql);
      if (n > 0)
        JOptionPane.showMessageDialog(null, "Deleted Data: ", "Confim", 1); 
      this.con.CerrarConexion();
      this.sentenciaSQL.close();
    }catch(Exception e){ System.out.println(e);
    }
  
    Metodos_Altas me = new Metodos_Altas();
   me.MostrarTablaYTDDetalladoMecanico(TablaDeduccionMecanicoYTD, txtperi2, txtnombre1, txtapellido1, año1);
  MostrarTablaDeduccionMecanico();
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NominaExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NominaExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NominaExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NominaExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NominaExtra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaDeduccionMecanico;
    public javax.swing.JTable TablaDeduccionMecanicoYTD;
    public javax.swing.JTable TablaDeduccionYTDMecanicoNombre;
    public javax.swing.JTable TablaDeduccoinesYTDTotal;
    public javax.swing.JTable TablaPagoMecanico;
    public javax.swing.JTable TablaSubTotal;
    public javax.swing.JTable TablaTotalDeducciones;
    public javax.swing.JTable TablaTotalDeducciones2;
    public javax.swing.JTable TablaTotalPay;
    public javax.swing.JTable TablaYTDSubTotal;
    private javax.swing.JComboBox<String> año;
    private javax.swing.JComboBox<String> año1;
    private javax.swing.JTextField bonus;
    private javax.swing.JTextField bonus1;
    public javax.swing.JButton g1;
    public javax.swing.JButton g2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JLabel nam;
    private javax.swing.JTextField pay;
    public javax.swing.JTable tabla2;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txtDeduccion;
    private javax.swing.JTextField txtDeduccionYTD;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JLabel txtapellido;
    private javax.swing.JTextField txtapellido1;
    private javax.swing.JTextField txtm;
    private javax.swing.JLabel txtnombre;
    private javax.swing.JTextField txtnombre1;
    private javax.swing.JTextField txtp;
    private javax.swing.JTextField txtperi;
    private javax.swing.JTextField txtperi2;
    private javax.swing.JTextField txtsub;
    private javax.swing.JTextField txtytds;
    // End of variables declaration//GEN-END:variables
}
