/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Controlador.ControladorExcel;
import Datos.AltaCamion;
import Datos.AltaChofer;
import Datos.AltaTrailer;
import Datos.AltaViaje;
import Metodos.Metodos_Altas;
import Metodos.Metodos_sql;
import Modelo.ModeloExcel;
import Puentes.puenteAltas;
import java.sql.Date;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author AlejandroSaenz
 */
public class NuevoViaje extends javax.swing.JFrame {
        DecimalFormat df=new DecimalFormat("#.00");

Metodos_sql Metodos2;

    /**
     * Creates new form NuevoViaje
     */
    public NuevoViaje() {
       
        this.Metodos2 = new Metodos_sql();
        this.Metodos = new Metodos_Altas();
        initComponents();
        BC.requestFocus();
        txtSantaJulia.setEnabled(false);
        
      
        BT.setEnabled(false);
        BTR.setEnabled(false);
      // this.ID.setText("" + obtenerId());
        txtAmount.setEnabled(false);
        txtDriverPay.setEnabled(false);
        txtViaje.setEnabled(false);
        txtperiodo.setEnabled(false);
        txtCosto.setEnabled(false);
            setLocationRelativeTo(null);
          
            


    } 
    Metodos_Altas Metodos;
    private int obtenerId() {
    int f = this.Metodos.consultaIdViaje();
    return f;
  }
    private int obtenerViaje(String Id, String nombre, String Apellido, String año) {
    Metodos_Altas Metodos = new Metodos_Altas();
    int f = Metodos.consultaViaje(txtperiodo,txtFirst,txtLast,txta);
    return f;
  }
    public void Limpiar() {
        b1.setText("0");
        b2.setText("Empty");
       // P.setText("");
   // this.txtFirst.setText("");
   // this.txtLast.setText("");
   // this.txtTruck.setText("");
       this.txtAmount.setText("");
    this.txtDriverPay.setText("");
    this.txtPeso.setText("");
      //this.txtFecha1.setDateFormatString("");
    this.txtViaje.setText("");
   // this.txtTrailer.setText("");
    this.txtTicket.setText("");
   //ID.setText("");
   txtperiodo.setText("");
   txtperiodo.setText("");
   txtCosto.setText("");
   txtBol.setText("");
   txtDescripcion.setText("");
   txtPeso.setText("");
   //txtId_Driver.setText("");
  // Dueño.setText("");
 
   Distancia.setText("");
  }
    
  public void Calcular() {
      float PorcentajeTicket=(Float.parseFloat(por.getText()));
      float VariableSJ=Float.parseFloat(txtSantaJulia.getText());
      float resto= 100-PorcentajeTicket;
      float gasto;
      float Descuento;
      float porcentaje;
      float porcentaje2;
      float sueldo;
     gasto = (Float.parseFloat(txtCosto.getText()));
      //System.out.println(gasto);
     Descuento= (float) (gasto*(resto/100));
     Descuento=(float) (Descuento-VariableSJ);
     porcentaje=Integer.parseInt(P.getText());
      
      porcentaje2=porcentaje/100;
    
     sueldo= (float) (Descuento*porcentaje2);
      
      //System.out.println(sueldo);
     txtAmount.setText(" "+df.format(Descuento));
     txtDriverPay.setText(" "+df.format(sueldo));
     
   
    
  }
  public void Calcular2(){
    float total= (Float.parseFloat(txtCosto.getText()));
    float porcentaje=(Float.parseFloat(txtPorcentaje.getText()));
    porcentaje=porcentaje/100;
      Float SantaJulia=total*porcentaje;
      txtSantaJulia.setText(""+SantaJulia);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTicket = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtperiodo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtViaje = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtDriverPay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTruck = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTrailer = new javax.swing.JLabel();
        txtFecha1 = new com.toedter.calendar.JDateChooser();
        BC = new javax.swing.JTextField();
        BT = new javax.swing.JTextField();
        BTR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFirst = new javax.swing.JLabel();
        txtLast = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtCosto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtId_Driver = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtBol = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        combito = new javax.swing.JComboBox<>();
        Distancia = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Dueño = new javax.swing.JLabel();
        txta = new javax.swing.JComboBox<>();
        txtPeso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        por = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        bono = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bonoD = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtSantaJulia = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        b2 = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        txtN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(218, 165, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTicketActionPerformed(evt);
            }
        });
        txtTicket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTicketKeyTyped(evt);
            }
        });
        jPanel1.add(txtTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 127, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Id:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 25, -1, -1));

        ID.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 50, 18));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Driver");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Truck");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Trailer");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Weight:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Week:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        txtperiodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperiodoActionPerformed(evt);
            }
        });
        txtperiodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtperiodoKeyTyped(evt);
            }
        });
        jPanel1.add(txtperiodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 120, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("# Of Trip:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ticket:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        txtViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViajeActionPerformed(evt);
            }
        });
        txtViaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtViajeKeyTyped(evt);
            }
        });
        jPanel1.add(txtViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 121, -1));

        txtAmount.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtAmountComponentAdded(evt);
            }
        });
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 73, -1));

        txtDriverPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDriverPayActionPerformed(evt);
            }
        });
        jPanel1.add(txtDriverPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cost_of_the_trip:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amount:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Driver Pay");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Model:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        txtTruck.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        txtTruck.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(txtTruck, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 104, 23));

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Model:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        txtTrailer.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        txtTrailer.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(txtTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 105, 23));
        jPanel1.add(txtFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 90, 155, -1));

        BC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCActionPerformed(evt);
            }
        });
        BC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BCKeyTyped(evt);
            }
        });
        jPanel1.add(BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 51, -1));

        BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTActionPerformed(evt);
            }
        });
        BT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BTKeyTyped(evt);
            }
        });
        jPanel1.add(BT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 51, -1));

        BTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRActionPerformed(evt);
            }
        });
        BTR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BTRKeyTyped(evt);
            }
        });
        jPanel1.add(BTR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 51, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("first name:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Last Name:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        txtFirst.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        txtFirst.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 137, 14));

        txtLast.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        txtLast.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(txtLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 137, 14));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Añadir_16 .png"))); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, -1, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, -1, -1));

        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        txtCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 70, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Id_Driver:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, 20));

        txtId_Driver.setBackground(new java.awt.Color(255, 255, 255));
        txtId_Driver.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtId_Driver.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(txtId_Driver, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 40, 20));

        jButton2.setText("view");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 90, -1));

        jButton4.setText("view");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, -1));

        jButton5.setText("view");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Description_of_the_cost:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("BOL:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        txtBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBolActionPerformed(evt);
            }
        });
        jPanel1.add(txtBol, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 130, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Porcentage:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        P.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 50, 20));

        jButton6.setText("New");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, -1));

        combito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ton", "Pound" }));
        jPanel1.add(combito, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 120, 30));

        Distancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DistanciaKeyTyped(evt);
            }
        });
        jPanel1.add(Distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 80, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Year:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Distance:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, -1, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Owner:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        Dueño.setBackground(new java.awt.Color(255, 255, 255));
        Dueño.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Dueño.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(Dueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 180, 20));

        txta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));
        jPanel1.add(txta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 80, 30));

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoKeyTyped(evt);
            }
        });
        jPanel1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 110, 30));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 270, -1));

        por.setText("14.5");
        por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porActionPerformed(evt);
            }
        });
        por.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                porKeyTyped(evt);
            }
        });
        jPanel1.add(por, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 70, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Mi.");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 30, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("%");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 20, 20));

        bono.setText("0");
        bono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonoActionPerformed(evt);
            }
        });
        bono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bonoKeyTyped(evt);
            }
        });
        jPanel1.add(bono, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 150, 70, -1));

        bonoD.setColumns(20);
        bonoD.setRows(5);
        bonoD.setText("Empty");
        jScrollPane2.setViewportView(bonoD);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 220, 210, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Bonus Details:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Detention");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, -1, -1));

        txtPorcentaje.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(txtPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 50, 20));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Percentage:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Santa julia Freight Services:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        txtSantaJulia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSantaJuliaActionPerformed(evt);
            }
        });
        jPanel1.add(txtSantaJulia, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 73, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Fuel SC");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 350, -1, -1));

        b1.setText("0");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        b1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b1KeyTyped(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 350, 70, -1));

        b2.setColumns(20);
        b2.setRows(5);
        b2.setText("Empty");
        jScrollPane3.setViewportView(b2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 410, 210, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Bonus Details:");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 220, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText(" Ticket:");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        jToolBar1.setRollover(true);

        txtN.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txtN.setText("jLabel21");
        jToolBar1.add(txtN);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
ModeloExcel modeloE = new ModeloExcel();
        Sistema vistaE = new Sistema();
        ControladorExcel contraControladorExcel = new ControladorExcel(vistaE, modeloE);
        vistaE.setVisible(true);
        vistaE.nombreUsuario.setText(txtN.getText());
        vistaE.setLocationRelativeTo(null); 
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  if ( this.txtperiodo.getText().isEmpty() ||this.txtTicket.getText().isEmpty() ||this.bono.getText().isEmpty() ||this.bonoD.getText().isEmpty() || 
          this.txtLast.getText().isEmpty() || this.txtFirst.getText().isEmpty()|| this.por.getText().isEmpty()||
          this.txtTruck.getText().isEmpty()||this.txtTrailer.getText().isEmpty()|| this.txtViaje.getText().isEmpty()|| 
          this.txtTicket.getText().isEmpty()||
          this.txtPeso.getText().isEmpty()|| this.txtAmount.getText().isEmpty()||  this.txtBol.getText().isEmpty()||  this.txtDescripcion.getText().isEmpty()|| 
          this.txtDriverPay.getText().isEmpty()|| this.txtCosto.getText().isEmpty()|| txtFecha1.getDate() == null
          || this.Dueño.getText().isEmpty()|| this.Distancia.getText().isEmpty()|| this.b1.getText().isEmpty()|| this.b2.getText().isEmpty()) {
JOptionPane.showMessageDialog(null, "Please fill all fields", "empty fields", 1);    } else {
      AltaViaje prod = new AltaViaje();
      
      //prod.setId(Integer.parseInt(ID.getText()));
      prod.setPeriod(Integer.parseInt(txtperiodo.getText()));
      prod.setNo_Trip(Integer.parseInt(txtViaje.getText()));
      prod.setTicket(txtTicket.getText());
      prod.setBOL(txtBol.getText());
      prod.setTruck(txtTruck.getText());
      prod.setTrailer(txtTrailer.getText());

      java.util.Date fecha = txtFecha1.getDate();
      long d = fecha.getTime();
      java.sql.Date soloFecha = new java.sql.Date(d);
      prod.setDate(soloFecha);

      prod.setId_Driver(Integer.parseInt(txtId_Driver.getText()));
      prod.setFirst_Name(txtFirst.getText());
      prod.setLast_Name(txtLast.getText());
      prod.setWeight(Float.parseFloat(txtPeso.getText()));
      prod.setCost_of_the_trip(Float.parseFloat(txtCosto.getText()));
      prod.setDescription_of_the_cost(txtDescripcion.getText());
      prod.setAmount(Float.parseFloat(txtAmount.getText()));
      prod.setDriver_Pay(Float.parseFloat(txtDriverPay.getText()));

      prod.setBonus(Float.parseFloat(bono.getText()));
      prod.setBonus_Details(bonoD.getText());
      prod.setTicket_Percentage(por.getText());

      prod.setYear(Integer.parseInt(txta.getSelectedItem().toString()));
      prod.setType(combito.getSelectedItem().toString());
      prod.setAdded_By(txtN.getText());
      prod.setMiles(Distancia.getText());
      prod.setOwner(Dueño.getText());
      prod.setSJFS_Percentage(Float.parseFloat(txtPorcentaje.getText()));
      prod.setS_J_F_S(Float.parseFloat(txtSantaJulia.getText()));
      prod.setBonus_Driver(Float.parseFloat(b1.getText()));
      prod.setDetails_Bonus_Driver(b2.getText());
     // this.ID.setText("" + obtenerId());
      
       
      (new puenteAltas()).PuenteRegistroViaje(prod);
      Limpiar();
              txtViaje.setEnabled(false);
              //txtperiodo.setEnabled(false); comentado para no tener que reingresar el id del chofer

    //this.ID.setText("" + obtenerId());
     // this.txtId.setText("" + obtenerId());
    }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtAmountComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtAmountComponentAdded
         // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountComponentAdded

    private void BCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCActionPerformed
         txtId_Driver.setText(BC.getText()); 
        if (!this.BC.getText().isEmpty()) {
     
      AltaChofer prov = new AltaChofer();
      prov.setId(Integer.parseInt(this.BC.getText()));
      (new puenteAltas()).PuenteBuscarChofer(prov);
      this.txtFirst.setText("" + prov.getNombre());
      this.txtLast.setText("" + prov.getApellidos());
      P.setText(""+prov.getPorcentaje());
      BC.setText("");
      BT.requestFocus();
              txtperiodo.setEnabled(true);
            //  txtCosto.setEnabled(true);
             txtperiodo.requestFocus();
    } else {
      JOptionPane.showMessageDialog(null, "Enter a ID", "Warning", 1);
    }
         
    }//GEN-LAST:event_BCActionPerformed

    private void BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTActionPerformed
 if (!this.BT.getText().isEmpty()) {
     
      AltaCamion prov = new AltaCamion();
      prov.setId(Integer.parseInt(this.BT.getText()));
      (new puenteAltas()).PuenteBuscarCamion(prov);
      this.txtTruck.setText("" + prov.getModel());
      Dueño.setText(""+ prov.getOwner());
      txtPorcentaje.setText(""+prov.getPercentage());
      BT.setText("");
      txtCosto.setEnabled(true);
      BTR.requestFocus();
    } else {
      JOptionPane.showMessageDialog(null, "Enter a ID", "Warning", 1);}        // TODO add your handling code here:
    }//GEN-LAST:event_BTActionPerformed

    private void BTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRActionPerformed
if (!this.BTR.getText().isEmpty()) {
     
      AltaTrailer prov = new AltaTrailer();
      prov.setId(Integer.parseInt(this.BTR.getText()));
      (new puenteAltas()).PuenteBuscarTrailer(prov);
      this.txtTrailer.setText("" + prov.getModel());
            BTR.setText("");
            txtTicket.requestFocus();
    } else {
      JOptionPane.showMessageDialog(null, "Debes introducir un Numero de control", "Aviso", 1);}         // TODO add your handling code here:
    }//GEN-LAST:event_BTRActionPerformed

    private void txtperiodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperiodoActionPerformed
if (!this.txtperiodo.getText().isEmpty()) {
    txtTruck.setText("");
    Dueño.setText("");
    txtTrailer.setText("");
      this.txtViaje.setText("" + obtenerViaje(this.txtperiodo.getText(),txtFirst.getText(),txtLast.getText(),txta.getSelectedItem().toString()));
      AltaViaje prov = new AltaViaje();
      prov.setPeriod(Integer.parseInt(this.txtperiodo.getText()));
      prov.setFirst_Name(txtFirst.getText());
      prov.setLast_Name(txtLast.getText());
      
      
       String Busqueda_Mueble=Metodos_sql.Buscar_Muebles(txtFirst, txtLast, txtperiodo,txtTruck,txtTrailer,Dueño,txta,txtPorcentaje);
       JOptionPane.showMessageDialog(this, "Brand and model \n" + Busqueda_Mueble);
      txtTicket.requestFocus();
      txtCosto.setEnabled(true);
    } else {
      JOptionPane.showMessageDialog(null, "Debes introducir un Numero de Semana", "Aviso", 1);
    } 
        
        
                // TODO add your handling code here:
    }//GEN-LAST:event_txtperiodoActionPerformed

    private void txtViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViajeActionPerformed
txtTicket.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtViajeActionPerformed

    private void txtTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTicketActionPerformed
String BusquedaTicket = Metodos_sql.Buscar_Ticket(txtTicket.getText());
        if (BusquedaTicket.equals("Ticket ya existe")) {JOptionPane.showMessageDialog(null, "Ticket already exists"); txtTicket.setText("");}
        else{
        
        txtBol.requestFocus();     }   // TODO add your handling code here:
    }//GEN-LAST:event_txtTicketActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
txtDriverPay.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtDriverPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDriverPayActionPerformed
BC.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtDriverPayActionPerformed

    private void txtperiodoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtperiodoKeyTyped
char car = evt.getKeyChar();
    if (car < '0' || car > '9')
      evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_txtperiodoKeyTyped

    private void txtViajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtViajeKeyTyped
char car = evt.getKeyChar();
    if (car < '0' || car > '9')
      evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_txtViajeKeyTyped

    private void txtTicketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTicketKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTicketKeyTyped

    private void BCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BCKeyTyped
char car = evt.getKeyChar();
    if (car < '0' || car > '9')
      evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_BCKeyTyped

    private void BTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BTKeyTyped
char car = evt.getKeyChar();
    if (car < '0' || car > '9')
      evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_BTKeyTyped

    private void BTRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BTRKeyTyped
char car = evt.getKeyChar();
    if (car < '0' || car > '9')
      evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_BTRKeyTyped

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
if(txtCosto.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "Please enter an amount");
                                }
    else{
   
   Calcular2();
   Calcular();
txtDescripcion.requestFocus();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
TablaVariadona tv=new TablaVariadona();
tv.setVisible(true);
tv.MostrarTablaChofer();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
TablaVariadona tv=new TablaVariadona();
tv.setVisible(true);
tv.MostrarTablaCamion();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
TablaVariadona tv=new TablaVariadona();
tv.setVisible(true);
tv.MostrarTablaTrailer();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoKeyTyped
char car = evt.getKeyChar();
    if (car!='.'&&car!='0'&&car!='1'&&car!='2'&&car!='3'&&car!='4'&&car!='5'&&car!='6'&&car!='7'&&car!='8'&&car!='9')
      evt.consume();                 // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoKeyTyped

    private void txtBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBolActionPerformed
String BusquedaBOL = Metodos_sql.Buscar_Bol(txtBol.getText());
        if (BusquedaBOL.equals("BOL ya existe")) {JOptionPane.showMessageDialog(null, "BOL already exists"); txtBol.setText("");}
        else{
        
        txtBol.requestFocus();     }
        por.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBolActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
BT.setEnabled(true);
        BTR.setEnabled(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void DistanciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DistanciaKeyTyped
char car = evt.getKeyChar();
    if (car!='.'&&car!='0'&&car!='1'&&car!='2'&&car!='3'&&car!='4'&&car!='5'&&car!='6'&&car!='7'&&car!='8'&&car!='9')
      evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_DistanciaKeyTyped

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
Distancia.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void txtPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyTyped
char car = evt.getKeyChar();
    if (car!='.'&&car!='0'&&car!='1'&&car!='2'&&car!='3'&&car!='4'&&car!='5'&&car!='6'&&car!='7'&&car!='8'&&car!='9')
      evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoKeyTyped

    private void porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porActionPerformed
txtCosto.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_porActionPerformed

    private void porKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_porKeyTyped
char car = evt.getKeyChar();
    if (car!='.'&&car!='0'&&car!='1'&&car!='2'&&car!='3'&&car!='4'&&car!='5'&&car!='6'&&car!='7'&&car!='8'&&car!='9')
      evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_porKeyTyped

    private void bonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bonoActionPerformed

    private void bonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonoKeyTyped
char car = evt.getKeyChar();
    if (car!='.'&&car!='0'&&car!='1'&&car!='2'&&car!='3'&&car!='4'&&car!='5'&&car!='6'&&car!='7'&&car!='8'&&car!='9')
      evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_bonoKeyTyped

    private void txtSantaJuliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSantaJuliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSantaJuliaActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
   
    }//GEN-LAST:event_b1ActionPerformed

    private void b1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b1KeyTyped
char car = evt.getKeyChar();
    if (car!='.'&&car!='0'&&car!='1'&&car!='2'&&car!='3'&&car!='4'&&car!='5'&&car!='6'&&car!='7'&&car!='8'&&car!='9')
      evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_b1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField BC;
    private javax.swing.JTextField BT;
    private javax.swing.JTextField BTR;
    private javax.swing.JTextField Distancia;
    private javax.swing.JLabel Dueño;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel P;
    private javax.swing.JTextField b1;
    private javax.swing.JTextArea b2;
    private javax.swing.JTextField bono;
    private javax.swing.JTextArea bonoD;
    private javax.swing.JComboBox<String> combito;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField por;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBol;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDriverPay;
    private com.toedter.calendar.JDateChooser txtFecha1;
    public javax.swing.JLabel txtFirst;
    private javax.swing.JLabel txtId_Driver;
    public javax.swing.JLabel txtLast;
    public javax.swing.JLabel txtN;
    private javax.swing.JTextField txtPeso;
    public javax.swing.JLabel txtPorcentaje;
    private javax.swing.JTextField txtSantaJulia;
    private javax.swing.JTextField txtTicket;
    public javax.swing.JLabel txtTrailer;
    public javax.swing.JLabel txtTruck;
    private javax.swing.JTextField txtViaje;
    private javax.swing.JComboBox<String> txta;
    public javax.swing.JTextField txtperiodo;
    // End of variables declaration//GEN-END:variables
}
